### ISSUE TITLE
Installed version does ot work

### ISSUE THREAD

**Issue by p-snft** [Inovesa/Lisa#2]
I installed lisa using

    pip install .

inside the Lisa directory. However, loading does not work:

    In [1]: import lisa
    ---------------------------------------------------------------------------
    FileNotFoundError                         Traceback (most recent call last)
    <ipython-input-1-0fbd45f6c016> in <module>()
    ----> 1 import lisa

    ~/.local/lib/python3.5/site-packages/lisa/__init__.py in <module>()
          5 
          6 import os
    ----> 7 __version__ = open(os.path.join(os.path.dirname(__file__), "VERSION"), 'r').readline().strip()

    FileNotFoundError: [Errno 2] No such file or directory: '~/.local/lib/python3.5/site-packages/lisa/VERSION'

**Comment by pcsch** [comment]
This is a result of modifying the name to lowercase since in MANIFEST.in the installed file Lisa/VERSION cannot be found anymore and will not be installed.

**Comment by pcsch** [comment]
What is the reason for naming it lowercase?

**Comment by pcsch** [comment]
What is the reason for naming it lowercase?

**Comment by p-snft** [comment]
Ah! (The documentation for creating Python packages I found, stated to only use lowercase.)
